require:
  - standard/cop/semantic_blocks
  - rubocop-md

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'docs/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'spec/dummy/db/migrate/*_enable_hstore.rb'
    - 'spec/dummy/db/migrate/*_logidze_install.rb'
  DisplayCopNames: true
  TargetRubyVersion: 2.5

Standard/SemanticBlocks:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

Naming/FileName:
  Exclude:
    - 'lib/test-prof.rb'
    - '**/*.md'
